LqrLocalPlannerROS:
  # next point distance/turning angle
  p_window: 0.5
  # o_window: 1.0

  # goal reached tolerance
  p_precision: 0.2
  # o_precision: 0.5

  # linear velocity
  max_v: 1.0
  min_v: 0.0
  max_v_inc: 0.5

  # angular velocity
  max_w: 1.0
  min_w: 0.0
  max_w_inc: 1.0

  # lqr
  wheelbase: 0.5
  max_iter: 100
